version: '3'

networks: 
    laravel:
        driver: bridge

services: 
    nginx:
        image: nginx:alpine
        container_name: "laravel_nginx"
        restart: unless-stopped
        tty: true
        ports:
            - "8000:8000"
        volumes: 
            - ./:/var/www/app
            - ./default.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - php
            - postgres
        networks: 
            - laravel

    postgres:
        image: postgres:14.4-alpine
        container_name: "laravel_postgres"
        restart: unless-stopped
        tty: true
        ports:
            - "${DB_PORT}:5432"
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        networks:
            - laravel

    php:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel_docker:latest
        container_name: "laravel_php"
        restart: unless-stopped
        tty: true
        working_dir: /var/www/app
        volumes: 
            - ./:/var/www/app
        ports: 
            - "9000:9000"
        networks: 
            - laravel